name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.46.0
        with:
          ruby-version: 2.6
      - run: bundle install
      
      - name: Setup Vim
        uses: rhysd/action-setup-vim@v1.2.4
        with: 
          version: "stable"

      - name: Run a multi-line script
        run: neovim -v
