name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.46.0
        with:
          ruby-version: 2.6

      - name: Setup Vim
        uses: rhysd/action-setup-vim@v1.2.4
        with:
          neovim: true
          version: "stable"

      - name: Test
        run: |
          cd $GITHUB_WORKSPACE
          bundle install
          VSPEC_VIM=nvim rake ci
